
export const LOADING_GET_ALL_MUSICS = 'LOADING_GET_ALL_MUSICS'
export const SUCCESS_GET_ALL_MUSICS = 'SUCCESS_GET_ALL_MUSICS'
export const ERROR_GET_ALL_MUSICS = 'ERROR_GET_ALL_MUSICS'

export const LOADING_GET_MUSIC_BY_ID = 'LOADING_GET_MUSIC_BY_ID'
export const SUCCESS_GET_MUSIC_BY_ID = 'SUCCESS_GET_MUSIC_BY_ID'
export const ERROR_GET_MUSIC_BY_ID = 'ERROR_GET_MUSIC_BY_ID'

export const LOADING_RECOMMENDED_MUSICS = 'LOADING_RECOMMENDED_MUSICS'
export const SUCCESS_RECOMMENDED_MUSICS = 'SUCCESS_RECOMMENDED_MUSICS'
export const ERROR_RECOMMENDED_MUSICS = 'ERROR_RECOMMENDED_MUSICS'
