export const LOADING_PLAYER_MUSIC = 'LOADING_PLAYER_MUSIC'
export const ERROR_PLAYER_MUSIC = 'ERROR_PLAYER_MUSIC'
export const SUCCESS_PLAYER_MUSIC = 'SUCCESS_PLAYER_MUSIC'

export const START_MUSIC = 'START_MUSIC'
export const PAUSE_MUSIC = 'PAUSE_MUSIC'
export const STOP_MUSIC = 'STOP_MUSIC'
