export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR'

export const LOGOUT = 'LOGOUT'